###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Matias",
    "email": "carlos@gmail.com",
    "username": "carlos",
    "password": "12345"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63ab071fb0208bbd8cef6b34 HTTP/1.1

###
GET http://localhost:9000/api/users/login/carlos/12345 HTTP/1.1


###
PUT http://localhost:9000/api/users/63ab071fb0208bbd8cef6b34 HTTP/1.1
Content-Type: application/json

{
    "name": "Carla",
    "email": "carla@gmail.com",
    "name_user": "pokemon",
    "password": "12345"
}

###
DELETE http://localhost:9000/api/users/63ab08b0b0208bbd8cef6b36 HTTP/1.1

